### PR TITLE
Introduce bash-completion script

### PR DESCRIPTION
**Pull request by zippy2**

### CODE REVIEW

**Comment by thesamesam** [comment]
Thanks! I wonder if we should put it in gentoo-bashcomp instead. @arthurzam?

**Comment by arthurzam** [comment]
I think it would be better indeed.

**Comment by zippy2** [comment]
Fair enough. I've send it out as a patch. Only to find out there's a github mirror against which I could have opened a MR. Let me know if you want me to do that instead.

**Comment by arthurzam** [comment]
@thesamesam I've modified & improved the completion, and pushed to gentoo-bashcomp
I think we can close this PR.

**Comment by zippy2** [comment]
Agreed. Let me close this. Thanks everybody!

**Pull request closed without merging**
